# Generated by Django 5.2.4 on 2025-08-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_googlefittoken_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlefittoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
