# Generated by Django 5.2.4 on 2025-08-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_googlefittoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlefittoken',
            name='token_uri',
        ),
        migrations.AlterField(
            model_name='googlefittoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
