# Generated by Django 5.2.4 on 2025-08-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_googlefittoken_token_uri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlefittoken',
            name='token_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='googlefittoken',
            name='client_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='googlefittoken',
            name='client_secret',
            field=models.CharField(max_length=255),
        ),
    ]
