# Generated by Django 5.2.4 on 2025-08-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_googlefittoken_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlefittoken',
            name='scopes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
